server:
  port: 8081

spring:
  kafka:
    # 指定kafka代理地址，可以是多个kafka地址
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    # ---------------- 生产者配置 ----------------
    producer:
      retries: 0 # 设置大于0的值，则客户端会将发送失败的记录重新发送

      batch-size: 16384 # 每次批量发送消息的数量
      buffer-memory: 33554432

      # 指定消息key和消息体的编解码方式：utf-8
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      # 消息发送策略，默认为0：at least once，1：at most once，all：exactly once
      acks: 0

    # ---------------- 消费者配置 ----------------
    consumer:
      group-id: lockeGroup # 指定默认消费者组名，由于kafka中同一组consumer不会读取同一个消息

      auto-offset-reset: earliest

      enable-auto-commit: true # 是否自动提交offset
      auto-commit-interval: 100 # 上一行自动提交offset时，此行为提交的频率，单位毫秒，默认为5000

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
