server:
  port: 8081

spring:
  application:
    name: provider-ticket # 当前服务的名称

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/